### ISSUE TITLE
not work on specific machine

### ISSUE THREAD

**Issue by WXZhao7** [sourcery-ai/sourcery-vscode#110]
Today I found there is no suggestion from Sourcery and then recognized it does not work.
![sourcery-error](https://user-images.githubusercontent.com/56864878/204490056-8d349c1d-06a6-4b76-8361-3e8ccf98e55f.png)
I disable the unrelated extensions and only keep Soucery and recommended python packages on. But nothing changed. Finally, I try to reproduce the error in a VM. I downloaded VScode, copy the `setting.json` and install the same extension. Everything worked well. 
![sourcery-ok](https://user-images.githubusercontent.com/56864878/204490304-17f8bd99-9994-4b44-971c-c777de499187.png)
I also uninstall sourcery and even delete `~/.config/sourcery/auth.yaml` then reinstall it, but the soucery still can't show any suggestion. I need help :(
![image](https://user-images.githubusercontent.com/56864878/204490965-2f4b49ed-796f-445a-b66a-0fb72a078f1e.png)

**Comment by Hellebore** [comment]
Thanks for raising, and sorry you're having issues.

Could you let us know:
- The OS of the machine
- Whether it previously worked on this machine
- Have you got a `.sourcery.yaml` file in the project of a `sourcey.yaml` file in your user config location:
https://docs.sourcery.ai/Reference/Configuration/Sources/#user-configuration-file-system-locations

Could you also post (or mail to support@sourcery.ai) your log file:
https://docs.sourcery.ai/Product/Troubleshooting/#what-is-the-sourcery-log

**Comment by WXZhao7** [comment]
@Hellebore Thanks. I work with Ubuntu20.04, and VM is also Ubuntu20.04. I did not use any `sourcey.yaml` and emailed logs to [support@sourcery.ai](mailto:support@sourcery.ai).

**Comment by WXZhao7** [comment]
I'm sure [sourcery-vscode](https://github.com/sourcery-ai/sourcery-vscode) worked for a long time. But I'm not clear when it stopped working😱

**Comment by WXZhao7** [comment]
@Hellebore Somthing wrong in v1.0.0+
v0.12.12 ✅
![image](https://user-images.githubusercontent.com/56864878/204504303-dcc227e3-0aa1-48c2-96fa-a5f2443c1d7c.png)
v0.12.13 ✅
![image](https://user-images.githubusercontent.com/56864878/204507106-c9016816-d3f2-401e-b473-3fffb16f7959.png)
v1.0.0 and v1.0.1 ❌
![image](https://user-images.githubusercontent.com/56864878/204508019-7c8cedc8-a1d9-4972-8d3a-0c6ab9322b2c.png)

**Comment by WXZhao7** [comment]
I'm sure I can't find any `sourcery.yaml`.
![image](https://user-images.githubusercontent.com/56864878/204536612-6980517b-a046-462d-916e-6b30d69cf67d.png)
even in the example repo dir, also no `sourcery.yaml `
![image](https://user-images.githubusercontent.com/56864878/204536977-dd302e69-282e-4d2c-ab39-0e8452067720.png)

**Comment by WXZhao7** [comment]
I also never use `sourcery.yaml` in my projects.
![image](https://user-images.githubusercontent.com/56864878/204538964-28a502b4-ac0d-4896-ad89-31336210df91.png)

![image](https://user-images.githubusercontent.com/56864878/204538909-461cd442-3ea2-45ce-82f2-1774452ff178.png)

**Comment by Hellebore** [comment]
Thanks - this is really helpful.

Could you also look in `~/.local/share/sourcery/sourcery.yaml` for me please?

**Comment by Hellebore** [comment]
This is really puzzling. It's behaving exactly as if you have a yaml file with an invalid config somewhere!

Could you search your whole system for `.sourcery.yaml' files?

(like go to your home and use `find . -name '.sourcery.yaml'`)

Also are `wxz` and `wxzhao` aliased on your system or are they separate directories?

If that doesn't work we will add more logging to our next version to see if that can find the problem.

**Comment by WXZhao7** [comment]
Yeah, I find the hidden `.sourcery.yaml`. Removed it and Sourcery worked again! Thanks!❤️
![image](https://user-images.githubusercontent.com/56864878/204574481-c05fdb8d-aef8-4c5f-b822-a9e945f7a96a.png)
```yml
# 🪄 This is your project's Sourcery configuration file.

# You can use it to get Sourcery working in the way you want, such as
# ignoring specific refactorings, skipping directories in your project,
# or writing custom rules.

# 📚 For a complete reference to this file, see the documentation at
# https://docs.sourcery.ai/Configuration/Project-Settings/

# This file was auto-generated by Sourcery on 2022-06-17 at 08:49.

version: '1'  # The schema version of this config file

ignore: # A list of paths or files which Sourcery will ignore.
- .git
- venv
- .venv
- env
- .env

refactor:
  include: []
  skip: []  # A list of rule IDs Sourcery will never suggest.
  rule_types:
  - refactoring
  - suggestion
  - comment
  python_version: '3.9'  # A string specifying the lowest Python version your project supports. Sourcery will not suggest refactorings requiring a higher Python version.

# rules:  # A list of custom rules Sourcery will include in its analysis.
# - id: no-print-statements
#   description: Disallows print statements anywhere in code.
#   pattern: print
#   replacement:
#   explanation:
#   paths:
#     include:
#     - test
#     exclude:
#     - conftest.py
#   tests: []

# metrics:
#   quality_threshold: 25.0

# github:
#   labels: []
#   ignore_labels:
#   - sourcery-ignore
#   request_review: author
#   sourcery_branch: sourcery/{base_branch}

# clone_detection:
#   min_lines: 3
#   min_duplicates: 2
#   identical_clones_only: false

# proxy:
#   url:
#   ssl_certs_file:
#   no_ssl_verify: false
```

![image](https://user-images.githubusercontent.com/56864878/204575751-bd7438b1-50b4-4934-96f7-f7834e4d4a56.png)
